drop table if exists tb_cat_categoria CASCADE
;
drop table if exists tb_cur_curso CASCADE
;
drop table if exists tb_mat_materia CASCADE
;
create table tb_cat_categoria (cat_id bigint generated by default as identity, cat_nome varchar(255), primary key (cat_id))
;
create table tb_cur_curso (cur_id bigint generated by default as identity, cur_nome varchar(255), cat_id bigint, primary key (cur_id))
;
create table tb_mat_materia (mat_id bigint generated by default as identity, mat_nome varchar(255), cur_id bigint, primary key (mat_id))
;
alter table tb_cur_curso add constraint FKj6bgbb428ywek7dwyupkcub6r foreign key (cat_id) references tb_cat_categoria
;
alter table tb_mat_materia add constraint FKdkeg9tthvtvefor1rdc4f6tyh foreign key (cur_id) references tb_cur_curso
